<template>
  <!--prettier-ignore-->
  <article
    class="
      prose
      max-w-[100ch]
      prose-headings:text-slate-600
      prose-lead:w-[64ch]
      prose-p:mt-0
      prose-p:w-auto
      prose-p:before:content-none
      prose-p:after:content-non
      prose-a:break-words
      prose-a:text-lightblue-700
      prose-a:underline
      prose-a:underline-offset-2
      prose-blockquote:border-l-4
      prose-blockquote:border-yellow-400
      prose-blockquote:pl-6
      prose-blockquote:font-normal
      prose-blockquote:not-italic
      prose-strong:font-medium
      prose-code:bg-lightblue-50
      prose-code:px-[0.2em]
      prose-code:py-[0.1em]
      prose-code:font-normal
      prose-code:text-lightblue-700
      prose-code:before:content-none
      prose-code:after:content-none
      prose-pre:-mx-4
      prose-pre:rounded-none
      prose-pre:bg-lightblue-50
      prose-pre:p-4
      prose-pre:text-sm
      prose-pre:md:-mx-0
      prose-pre:xl:rounded
      md:p-12
      lg:prose-lg
      lg:prose-p:w-[64ch]
      lg:prose-pre:p-6
    ">
    <slot/>
  </article>
</template>
